version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    command: --port 6379
    expose:
      - "6379"

    ports: 
      - 6379:6379
# CREATE ROLE lhowsam LOGIN SUPERUSER PASSWORD 'password';
# ALTER USER lhowsam WITH PASSWORd '123'