version: '3.9'
services:
  backend:
    build: .
    ports:
      - 6000:6000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: "postgres:latest"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tmtodos-me
    #env_file:
    #  - .env # The name of your environment file (the one at the repository root)

    volumes:
      - .dbdata:/var/lib/postgresql


  redis:
    image: redis:latest
    ports: 
      - 3500:3500
