
version: '3.9'
services:
  backend:
    build: .
    ports:
      - 5001:5001
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  
  postgres:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tmtodos_me
      POSTGRES_HOST: tmtodos_db
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports: 
      - 12000:12000
